// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mravhuabqvbgxdzacjqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yYXZodWFicXZiZ3hkemFjanF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTM0MzksImV4cCI6MjA2OTU2OTQzOX0.jSSOVKmOyAly0T2jpI5qi76YaKbk2ilr7oMqQ_Gc0ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});